# Generated by Django 4.2.3 on 2023-08-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
