# Generated by Django 4.2.3 on 2023-08-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_sharedpost_post_shared_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content_type",
        ),
    ]
