# Generated by Django 4.2.3 on 2023-08-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="full_name",
        ),
    ]
